import './globals.css'
import { Poppins } from 'next/font/google'
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
const inter = Poppins ({ weight: "800", preload: false })

export const metadata = {
  title: 'Mostra',
  description: 'Generated by Best Team',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Analytics/>
      <SpeedInsights/>
        {children}
      </body>
    </html>
  )
}