/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KNlFKF5IWgo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Login() {
  return (
    <main className="flex-1 bg-muted/40 py-8 md:py-12">
      <div className="container">
        <div className="mb-8 md:mb-12 flex justify-center">
          <h1 className="text-3xl font-bold md:text-4xl">Login</h1>
        </div>
        <div className="grid gap-8 justify-center md:grid-cols-2 lg:grid-cols-2">
          <div className="flex flex-col items-center justify-center">
            <div className="mb-4 text-center">
              <h2 className="text-2xl font-bold">Welcome back!</h2>
              <p className="text-muted-foreground">Enter your username to login to your account.</p>
            </div>
            <div className="w-full max-w-md space-y-4">
              <div>
                <Label htmlFor="username">Username</Label>
                <Input id="username" type="text" placeholder="Enter your username" />
              </div>
              <Button className="w-full">Login</Button>
            </div>
          </div>
          <div className="hidden md:flex flex-col items-center justify-center">
            <img
              src="/placeholder.svg"
              width={600}
              height={600}
              alt="QR Code"
              className="w-full max-w-[600px] rounded-lg"
            />
          </div>
        </div>
      </div>
    </main>
  )
}
